name: zfx_action_6
description: A sample dartemis application
dependencies:
  browser: any
  canvas_query: any
  dart_to_js_script_rewriter: any
  dartemis:
    path: ../dartemis
  gamedev_helpers:
    path: ../gamedev_helpers
  hop: any
  intl: any
  lawndart: any
transformers:
- dart_to_js_script_rewriter
- dartemis
